--------------------------------------------------------
--  File created - Friday-December-08-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CLAN_KLUBA
--------------------------------------------------------

  CREATE TABLE "MATIC"."CLAN_KLUBA" 
   (	"ID_CLANA" NUMBER, 
	"IME" VARCHAR2(20 BYTE), 
	"PREZIME" VARCHAR2(20 BYTE), 
	"CLANARINA" CHAR(1 BYTE), 
	"ID_KONTAKTA" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table KONTAKT
--------------------------------------------------------

  CREATE TABLE "MATIC"."KONTAKT" 
   (	"ID_KONTAKTA" NUMBER, 
	"ULICA" VARCHAR2(20 BYTE), 
	"BROJ" VARCHAR2(20 BYTE), 
	"MESTO" VARCHAR2(20 BYTE), 
	"EMAIL" VARCHAR2(20 BYTE), 
	"TELEFON" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table OSOBLJE
--------------------------------------------------------

  CREATE TABLE "MATIC"."OSOBLJE" 
   (	"ID_OSOBLJA" NUMBER, 
	"IME" VARCHAR2(20 BYTE), 
	"PREZIME" VARCHAR2(20 BYTE), 
	"SLOBODAN" CHAR(1 BYTE), 
	"ID_KONTAKT" NUMBER(*,0), 
	"ID_POSLA" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table POSAO
--------------------------------------------------------

  CREATE TABLE "MATIC"."POSAO" 
   (	"ID_POSLA" NUMBER, 
	"NAZIV" VARCHAR2(20 BYTE), 
	"OPIS" VARCHAR2(20 BYTE), 
	"CENA" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TRETMAN
--------------------------------------------------------

  CREATE TABLE "MATIC"."TRETMAN" 
   (	"ID_TRETMANA" NUMBER, 
	"ID_POSLA" NUMBER, 
	"ID_CLANA" NUMBER, 
	"ID_OSOBLJA" NUMBER, 
	"VREME" DATE, 
	"POPUST" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Sequence CLAN_KLUBA_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "MATIC"."CLAN_KLUBA_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence KONTAKT_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "MATIC"."KONTAKT_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence OSOBLJE_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "MATIC"."OSOBLJE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence POSAO_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "MATIC"."POSAO_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence TRETMAN_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "MATIC"."TRETMAN_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
REM INSERTING into MATIC.CLAN_KLUBA
SET DEFINE OFF;
Insert into MATIC.CLAN_KLUBA (ID_CLANA,IME,PREZIME,CLANARINA,ID_KONTAKTA) values (1,'Marko','Popov','y',3);
Insert into MATIC.CLAN_KLUBA (ID_CLANA,IME,PREZIME,CLANARINA,ID_KONTAKTA) values (2,'Mom?ilo','Brankovi?','n',4);
Insert into MATIC.CLAN_KLUBA (ID_CLANA,IME,PREZIME,CLANARINA,ID_KONTAKTA) values (3,'Miroslav','Dobri?','y',5);
REM INSERTING into MATIC.KONTAKT
SET DEFINE OFF;
Insert into MATIC.KONTAKT (ID_KONTAKTA,ULICA,BROJ,MESTO,EMAIL,TELEFON) values (1,'Zarka Zrenjanina','13','Zrenjanin','mas@mail.com','1234567890');
Insert into MATIC.KONTAKT (ID_KONTAKTA,ULICA,BROJ,MESTO,EMAIL,TELEFON) values (2,'Miroslava Ilica','22','Mrcajevci','tren@mail.com','0680252327');
REM INSERTING into MATIC.OSOBLJE
SET DEFINE OFF;
Insert into MATIC.OSOBLJE (ID_OSOBLJA,IME,PREZIME,SLOBODAN,ID_KONTAKT,ID_POSLA) values (1,'Dragan','Savic','y',1,1);
Insert into MATIC.OSOBLJE (ID_OSOBLJA,IME,PREZIME,SLOBODAN,ID_KONTAKT,ID_POSLA) values (2,'PETAR','JOVANOV','y',2,2);
REM INSERTING into MATIC.POSAO
SET DEFINE OFF;
Insert into MATIC.POSAO (ID_POSLA,NAZIV,OPIS,CENA) values (1,'Masažer','Masaža lica i tela',5000);
Insert into MATIC.POSAO (ID_POSLA,NAZIV,OPIS,CENA) values (3,'Trener','Licni trener',2500);
REM INSERTING into MATIC.TRETMAN
SET DEFINE OFF;
Insert into MATIC.TRETMAN (ID_TRETMANA,ID_POSLA,ID_CLANA,ID_OSOBLJA,VREME,POPUST) values (1,1,1,1,to_date('11-DEC-17','DD-MON-RR'),30);
Insert into MATIC.TRETMAN (ID_TRETMANA,ID_POSLA,ID_CLANA,ID_OSOBLJA,VREME,POPUST) values (2,2,2,2,to_date('27-DEC-17','DD-MON-RR'),20);
--------------------------------------------------------
--  DDL for Index POSAO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "MATIC"."POSAO_PK" ON "MATIC"."POSAO" ("ID_POSLA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index OSOBLJE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "MATIC"."OSOBLJE_PK" ON "MATIC"."OSOBLJE" ("ID_OSOBLJA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index CLAN_KLUBA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "MATIC"."CLAN_KLUBA_PK" ON "MATIC"."CLAN_KLUBA" ("ID_CLANA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index KONTAKT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "MATIC"."KONTAKT_PK" ON "MATIC"."KONTAKT" ("ID_KONTAKTA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index TRETMAN_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "MATIC"."TRETMAN_PK" ON "MATIC"."TRETMAN" ("ID_TRETMANA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Trigger CLAN_KLUBA_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "MATIC"."CLAN_KLUBA_TRG" 
BEFORE INSERT ON CLAN_KLUBA 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "MATIC"."CLAN_KLUBA_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger KONTAKT_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "MATIC"."KONTAKT_TRG" 
BEFORE INSERT ON KONTAKT 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID_KONTAKTA IS NULL THEN
      SELECT KONTAKT_SEQ.NEXTVAL INTO :NEW.ID_KONTAKTA FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "MATIC"."KONTAKT_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger OSOBLJE_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "MATIC"."OSOBLJE_TRG" 
BEFORE INSERT ON OSOBLJE 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "MATIC"."OSOBLJE_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger POSAO_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "MATIC"."POSAO_TRG" 
BEFORE INSERT ON POSAO 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID_POSLA IS NULL THEN
      SELECT POSAO_SEQ.NEXTVAL INTO :NEW.ID_POSLA FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "MATIC"."POSAO_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRETMAN_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "MATIC"."TRETMAN_TRG" 
BEFORE INSERT ON TRETMAN 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "MATIC"."TRETMAN_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRETMAN_TRG1
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "MATIC"."TRETMAN_TRG1" 
BEFORE INSERT ON TRETMAN 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID_TRETMANA IS NULL THEN
      SELECT TRETMAN_SEQ.NEXTVAL INTO :NEW.ID_TRETMANA FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "MATIC"."TRETMAN_TRG1" ENABLE;
--------------------------------------------------------
--  Constraints for Table KONTAKT
--------------------------------------------------------

  ALTER TABLE "MATIC"."KONTAKT" ADD CONSTRAINT "KONTAKT_PK" PRIMARY KEY ("ID_KONTAKTA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "MATIC"."KONTAKT" MODIFY ("TELEFON" NOT NULL ENABLE);
  ALTER TABLE "MATIC"."KONTAKT" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "MATIC"."KONTAKT" MODIFY ("MESTO" NOT NULL ENABLE);
  ALTER TABLE "MATIC"."KONTAKT" MODIFY ("BROJ" NOT NULL ENABLE);
  ALTER TABLE "MATIC"."KONTAKT" MODIFY ("ULICA" NOT NULL ENABLE);
  ALTER TABLE "MATIC"."KONTAKT" MODIFY ("ID_KONTAKTA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table POSAO
--------------------------------------------------------

  ALTER TABLE "MATIC"."POSAO" ADD CONSTRAINT "POSAO_PK" PRIMARY KEY ("ID_POSLA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "MATIC"."POSAO" MODIFY ("CENA" NOT NULL ENABLE);
  ALTER TABLE "MATIC"."POSAO" MODIFY ("OPIS" NOT NULL ENABLE);
  ALTER TABLE "MATIC"."POSAO" MODIFY ("NAZIV" NOT NULL ENABLE);
  ALTER TABLE "MATIC"."POSAO" MODIFY ("ID_POSLA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TRETMAN
--------------------------------------------------------

  ALTER TABLE "MATIC"."TRETMAN" ADD CONSTRAINT "TRETMAN_PK" PRIMARY KEY ("ID_TRETMANA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "MATIC"."TRETMAN" MODIFY ("VREME" NOT NULL ENABLE);
  ALTER TABLE "MATIC"."TRETMAN" MODIFY ("ID_OSOBLJA" NOT NULL ENABLE);
  ALTER TABLE "MATIC"."TRETMAN" MODIFY ("ID_CLANA" NOT NULL ENABLE);
  ALTER TABLE "MATIC"."TRETMAN" MODIFY ("ID_POSLA" NOT NULL ENABLE);
  ALTER TABLE "MATIC"."TRETMAN" MODIFY ("ID_TRETMANA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table OSOBLJE
--------------------------------------------------------

  ALTER TABLE "MATIC"."OSOBLJE" MODIFY ("ID_KONTAKT" NOT NULL ENABLE);
  ALTER TABLE "MATIC"."OSOBLJE" MODIFY ("ID_POSLA" NOT NULL ENABLE);
  ALTER TABLE "MATIC"."OSOBLJE" ADD CONSTRAINT "OSOBLJE_PK" PRIMARY KEY ("ID_OSOBLJA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "MATIC"."OSOBLJE" MODIFY ("SLOBODAN" NOT NULL ENABLE);
  ALTER TABLE "MATIC"."OSOBLJE" MODIFY ("PREZIME" NOT NULL ENABLE);
  ALTER TABLE "MATIC"."OSOBLJE" MODIFY ("IME" NOT NULL ENABLE);
  ALTER TABLE "MATIC"."OSOBLJE" MODIFY ("ID_OSOBLJA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CLAN_KLUBA
--------------------------------------------------------

  ALTER TABLE "MATIC"."CLAN_KLUBA" MODIFY ("ID_KONTAKTA" NOT NULL ENABLE);
  ALTER TABLE "MATIC"."CLAN_KLUBA" MODIFY ("CLANARINA" NOT NULL ENABLE);
  ALTER TABLE "MATIC"."CLAN_KLUBA" MODIFY ("PREZIME" NOT NULL ENABLE);
  ALTER TABLE "MATIC"."CLAN_KLUBA" MODIFY ("IME" NOT NULL ENABLE);
  ALTER TABLE "MATIC"."CLAN_KLUBA" ADD CONSTRAINT "CLAN_KLUBA_PK" PRIMARY KEY ("ID_CLANA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "MATIC"."CLAN_KLUBA" MODIFY ("ID_CLANA" NOT NULL ENABLE);
